# yamllint disable rule:comments-indentation
name: MasterCI

on: # yamllint disable-line rule:truthy
  push

jobs:
  CherryPick:
    runs-on: ubuntu-latest
    steps:
      - name: Set envs
        # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#multiline-strings
        run: |
          git clone --recursive --shallow-submodules https://github.com/ClickHouse/ClickHouse.git
      - name: Check out repository code
        run: |
          ls -al
      - name: Auto-release
        run: |
          cd "$GITHUB_WORKSPACE/tests/ci"
          python3 auto_release.py --release-after-days=3
      - name: Cleanup
        if: always()
        run: |
          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
          sudo rm -fr "$TEMP_PATH"
