# yamllint disable rule:comments-indentation
name: MasterCI

on: # yamllint disable-line rule:truthy
  push

jobs:
  CherryPick:
    runs-on: ubuntu-latest
    steps:
      - name: aaa
        run: |
          docker ps
          ping -c 5 registry.cn-hangzhou.aliyuncs.com    

      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: bbb
        run: |
          ls -al
          du -chs *
          docker ps

      - name: Cleanup
        run: |
          # define a directory for the output artifacts
          echo 123
#
#          output_dir="build_results"
#          mkdir -p build_results
#          ./docker/packager/packager --package-type=binary --output-dir "$output_dir"
#          ls -al build_results
