# yamllint disable rule:comments-indentation
name: MasterCI

on: # yamllint disable-line rule:truthy
  push

jobs:
  CherryPick:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Check out repository code
        run: |
          ls -al
      - name: Cleanup
        run: |
          # define a directory for the output artifacts
          output_dir="build_results"
          mkdir -p build_results
          ./docker/packager/packager --package-type=binary --output-dir "$output_dir"
          ls -al build_results
